#!/bin/bash
# serve a static pyjamas AUR (no RPC)

exec 3> /dev/null

spushd () { pushd ${1} >&3; }
spopd () { popd >&3; }

spushd $(dirname $(readlink -f ${0}))/out
python -m SimpleHTTPServer

spopd
exit 0
