#!/bin/bash
# compile pyjamas AUR app into deployable JS application

exec 3> /dev/null

spushd () { pushd ${1} >&3; }
spopd () { popd >&3; }
fatal () { echo "${1}"; exit 1; }

BASE=$(dirname ${0})
spushd ${BASE}

: ${PYJS_EXEC:=}
PYJS_EXEC_POSSIBLE=(
    "${PYJS_EXEC}"
    "${BASE}/.pyjs/bin/pyjsbuild"
    "${BASE}/../.pyjs/bin/pyjsbuild"
    "$(which pyjsbuild 2>&-)"
)

! [ -e "${PYJS_EXEC}" ] && {
    for x in ${PYJS_EXEC_POSSIBLE[@]}; do
        if [ -e "${x}" ]; then
            PYJS_EXEC=${x}
            break
        fi
    done
}

# last try
if ! [ -e "${PYJS_EXEC}" ]; then
    ./init 'true' || fatal 'could not find PYJS_EXEC (pyjsbuild)'
    PYJS_EXEC="${BASE}/.pyjs/bin/pyjsbuild"
fi

# don't remove the folder; SimpleHTTPServer could be running
rm -rf out/*

# build AUR
spushd src
${PYJS_EXEC} -mcO --bootstrap-file='Aur.js' --output='../out' Aur.py
spopd

# copy pub folder to out
cp -R pub/* out

spopd
exit 0
