#!/bin/bash
# compile pyjamas AUR app into deployable JS application

exec 3> /dev/null

spushd () { pushd ${1} >&3; }
spopd () { popd >&3; }

spushd $(dirname ${0})

PYJS_BOX_EXEC=$(pwd)/.pyjs/bin/pyjsbuild
PYJS_SYS_EXEC=$(which pyjsbuild 2>&-)

if [ ! -e "${PYJS_BOX_EXEC}" -a ! -e "${PYJS_SYS_EXEC}" ]; then
    ./init 'true' || { echo 'could not find PYJS_EXEC (pyjsbuild)'; exit 1; }
    PYJS_EXEC=${PYJS_BOX_EXEC}
elif [ -e "${PYJS_BOX_EXEC}" ]; then
    PYJS_EXEC=${PYJS_BOX_EXEC}
else
    PYJS_EXEC=${PYJS_SYS_EXEC}
fi

# don't remove the folder; SimpleHTTPServer could be running
rm -rf out/*

# build AUR
spushd src
${PYJS_EXEC} -mcO --bootstrap-file="Aur.js" --output="../out" Aur.py
spopd

# copy pub folder to out
cp -R pub/* out

spopd
exit 0
