#!/bin/bash
# bootstrap pyjamas AUR + optionally create devel environment in $HOME

exec 3> /dev/null

spushd () { pushd ${1} >&3; }
spopd () { popd >&3; }
fatal () { echo ${1}; exit 1; }

BASE=$(dirname $(readlink -f ${0}))
LOCAL=${HOME}/aur-pyjs
REMOTE=git://github.com/extofme/aur-pyjs.git
SANDBOX_ONLY=${1:-false}

! ${SANDBOX_ONLY} && [ -z "${HOME}" ] && fatal '$HOME is not set'

create_or_update_sandbox () {

    spushd ${BASE}

    if [ -e .pyjs/.git ]; then
        git --git-dir=.pyjs/.git pull
    else
        git clone git://pyjs.org/git/pyjamas.git .pyjs
    fi  

    # run bootstrap everytime
    if [ -d .pyjs ]; then
        spushd .pyjs
        make local-build || fatal 'problem bootstrapping pyjs sandbox'
        spopd
    fi  

    spopd

}

if ! ${SANDBOX_ONLY}; then
    if ! [ -e "${LOCAL}" ]; then
        git clone ${REMOTE} ${LOCAL}
        BASE=${LOCAL}
    elif [ -x "${LOCAL}/init" ]; then
        exec ${LOCAL}/init 'true'
    else
        fatal "${LOCAL} exists, but appears foreign"
    fi
fi

create_or_update_sandbox

exit 0
