#!/bin/bash
#
# no args       : makepkg PKGBUILD only
# $1 = 'true'   : + install locally
# $2 = 'true'   : + upload to AUR [legacy] (trigger update)
#
# ./install <local_install> <upload_to_aur>

LOCAL_IS_MAINTAINER=false

MAINTAINER=extofme
CATEGORY_ID=16
CATEGORY_NAME=devel

exec 3> /dev/null

BASE=$(dirname ${0})
LOCAL_INSTALL=${1:-false}
AUR_UPLOAD=${2:-false}
: ${AUR_UPLOAD_EXEC:=''}

${LOCAL_INSTALL} && makepkg_opts='-i'
${AUR_UPLOAD} && {
    do_aur () {
        echo ${AUR_UPLOAD_EXEC}
    }
} || {
    do_aur () {
        true
    }
}

spushd () { pushd ${1} >&3; }
spopd () { popd >&3; }
error() { echo "${1}"; }
fatal () { echo "${1}"; exit 1; }

spushd ${BASE}/pkg
makepkg -f ${makepkg_opts} || fatal 'Build failed'
do_aur || error 'AUR [legacy] sync failed'

spopd
exit 0
